In [1]:
import numpy as ny
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python untuk komputasi matriks

Matplotlib merupakan library python untuk presentasi data berapa grafik atau plot

Panda merupakan librari python untuk mengambil atau mengimpor data dari sumber luar, seperti Data.cvs

In [8]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

x berisi kolom Toko, Sepatu dan Hoodie

y berisi kolom Tempat (Label)

In [9]:
print(X)

[['Hustle' 44000.0 72000.0]
 ['Blackies' 89000.0 100000.0]
 ['Caro' 55000.0 54000.0]
 ['Caro' 45000.0 45000.0]
 ['Gangnam' 84000.0 nan]
 ['Blackies' 89000.0 100000.0]
 ['Caro' 55000.0 54000.0]
 ['Caro' nan 100000.0]
 ['Gangnam' 55000.0 55000.0]
 ['Hustle' 68000.0 99000.0]]


In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=ny.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

SimpleImputer merupakan fungsi untuk mengganti missing data (nan) dengan mencari rata - rata

In [12]:
print(X)

[['Hustle' 44000.0 72000.0]
 ['Blackies' 89000.0 100000.0]
 ['Caro' 55000.0 54000.0]
 ['Caro' 45000.0 45000.0]
 ['Gangnam' 84000.0 75444.44444444444]
 ['Blackies' 89000.0 100000.0]
 ['Caro' 55000.0 54000.0]
 ['Caro' 64888.88888888889 100000.0]
 ['Gangnam' 55000.0 55000.0]
 ['Hustle' 68000.0 99000.0]]


In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
X = ny.array(ct.fit_transform(X))

ct adalah variabel pemanggil ColumnTransformer

OneHotEncoder berfungsi untuk merubah dari nominal menjadi matriks

In [14]:
print(X)

[[0.0 0.0 0.0 1.0 44000.0 72000.0]
 [1.0 0.0 0.0 0.0 89000.0 100000.0]
 [0.0 1.0 0.0 0.0 55000.0 54000.0]
 [0.0 1.0 0.0 0.0 45000.0 45000.0]
 [0.0 0.0 1.0 0.0 84000.0 75444.44444444444]
 [1.0 0.0 0.0 0.0 89000.0 100000.0]
 [0.0 1.0 0.0 0.0 55000.0 54000.0]
 [0.0 1.0 0.0 0.0 64888.88888888889 100000.0]
 [0.0 0.0 1.0 0.0 55000.0 55000.0]
 [0.0 0.0 0.0 1.0 68000.0 99000.0]]


Menjadi bentuk matriks ORDE 4, jika dirun ColumntTransformer sekali lagi maka akan menjadi ORDE 5, dan seterusnya

In [15]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
